// React/src/App.js
import { useCallback } from 'react';

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import './App.css';

import {
    DataGrid,
    Column,
    Selection,
    FilterRow,
    GroupPanel,
    Pager,
    StateStoring
} from 'devextreme-react/data-grid';
import { orders } from './data';

const storageKey = "datagrid-state";
const allowedPageSizes = [5, 10, 20];

function App() {
    const loadState = useCallback(() => {
        return JSON.parse(localStorage.getItem(storageKey));
    }, []);

    const saveState = useCallback((state) => {
        if (state) {
            for (let i = 0; i < state.columns.length; i++) {
                state.columns[i].filterValue = null;
            }
        }
        localStorage.setItem(storageKey, JSON.stringify(state));
    }, []);
    
    return (
        <div className="App">
            <DataGrid
                dataSource={orders}
                keyExpr="ID"
                allowColumnResizing={true}
                allowColumnReordering={true}
                showBorders={true}>
                <Column dataField="OrderNumber" caption="Invoice Number" width={130} />
                <Column dataField="OrderDate" sortOrder="desc" dataType="date" />
                <Column dataField="SaleAmount" alignment="right" format="currency" />
                <Column dataField="Employee" />
                <Column dataField="CustomerStoreCity" caption="City" />
                <Column dataField="CustomerStoreState" caption="State" groupIndex={0} />
                <Selection mode="single" />
                <FilterRow visible={true} />
                <GroupPanel visible={true} />
                <Pager showPageSizeSelector={true} allowedPageSizes={allowedPageSizes} />
                <StateStoring
                    enabled={true}
                    type="custom"
                    storageKey={storageKey}
                    customLoad={loadState}
                    customSave={saveState}
                />
            </DataGrid>
        </div>
    );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Order, Service } from './app.service';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    providers: [Service]
})
export class AppComponent {
    orders: Order[];
    storageKey: string = "datagrid-state";

    constructor(private service: Service) {
        this.orders = service.getOrders();
    }
    loadState() {
        return JSON.parse(localStorage.getItem(this.storageKey));
    }
    saveState(state) {
        if (state) {
            for (let i = 0; i < state.columns.length; i++) {
                state.columns[i].filterValue = null;
            }
        }
        localStorage.setItem(this.storageKey, JSON.stringify(state));
    }
}

<div class="default-style">
    <dx-data-grid
        [dataSource]="orders"
        [allowColumnResizing]="true"
        [allowColumnReordering]="true"
        [showBorders]="true"
        keyExpr="ID">
        <dxi-column
            dataField="OrderNumber"
            [width]="130"
            caption="Invoice Number">
        </dxi-column>
        <dxi-column
            dataField="OrderDate"
            sortOrder="desc"
            dataType="date">
        </dxi-column>
        <dxi-column
            dataField="SaleAmount"
            alignment="right"
            format="currency">
        </dxi-column>
        <dxi-column dataField="Employee"></dxi-column>
        <dxi-column dataField="CustomerStoreCity" caption="City"></dxi-column>
        <dxi-column
            dataField="CustomerStoreState"
            caption="State"
            [groupIndex]="0">
        </dxi-column>
        <dxo-selection mode="single"></dxo-selection>
        <dxo-filter-row [visible]="true"></dxo-filter-row>
        <dxo-group-panel [visible]="true"></dxo-group-panel>
        <dxo-pager
            [showPageSizeSelector]="true"
            [allowedPageSizes]="[5, 10, 20]">
        </dxo-pager>
        <dxo-state-storing
            [enabled]="true"
            type="custom"
            [storageKey]="storageKey"
            [customLoad]="loadState"
            [customSave]="saveState">
        </dxo-state-storing>
    </dx-data-grid>
</div>
